import type { UiLanguage } from "../runtime/ui-preferences";
import type { BaseCollaborationChatLabels } from "./collaboration-chat-widget-types";

function buildLabels(language: UiLanguage, primaryDisplayName: string): BaseCollaborationChatLabels {
  if (language === "zh") {
    return {
      title: "协作群聊",
      subtitle: `与 ${primaryDisplayName} 和全部 AI 员工协同处理项目`,
      open: "展开协作群聊",
      close: "收起协作群聊",
      refresh: "刷新",
      autoOn: "自动刷新: 开",
      autoOff: "自动刷新: 关",
      creating: "正在创建对话...",
      deleting: "正在删除对话...",
      newChat: "新建对话",
      deleteChat: "删除对话",
      send: "发送",
      terminate: "终止",
      markDone: "已完成",
      markFollowUp: "待继续",
      markError: "报错",
      attach: "添加文件",
      upload: "上传中",
      mentions: "提及员工",
      route: "路由",
      unread: "未读",
      typingHint: "输入消息并使用 @ 指定员工；不带 @ 时默认先发给 Jarvis 协调",
      routeDefault: "默认路由给 Jarvis 协调",
      routePrefix: "当前路由到",
      routeAllMembers: "全员",
      roomLocked: "当前未开启写入解锁，无法切换实时对话或发送消息。",
      roomUnavailable: "当前环境没有可用的本地写入口令，协作群聊保持只读。",
      noEvents: "这个对话还没有消息。",
      noRooms: "暂时还没有可显示的对话。",
      save: "保存",
      openFile: "打开",
      download: "下载",
      preview: "预览",
      queued: "待发送",
      dispatching: "分发中",
      idle: "在线",
      failed: "失败",
      retrying: "重试中",
      createPrompt: "给这个新对话起个标题（可留空）",
      projectPrompt: "先给这个新对话绑定一个项目名称",
      projectRequired: "项目名称不能为空。",
      deleteConfirm:
        "确认删除这个对话吗？这会同时删除对应的本地协作记录、相关本地文件，以及 OpenClaw 原始聊天记录。",
      sending: "正在发送消息...",
      terminating: "正在终止当前工作...",
      adjudicating: "正在更新房间状态...",
      loading: "正在加载协作对话...",
      refreshed: "已刷新",
      writeUnavailable: "未配置写入口令",
      writeLocked: "写入解锁已关闭",
      writeReady: "写入已开启",
      pickedFiles: "已选文件",
      remove: "移除",
      roomsHeading: "对话列表",
      participantsHeading: "员工",
      currentRoom: "当前对话",
      conversation: "Collaboration Room",
      justNow: "刚刚",
      projectLabel: "项目",
      projectSummaryLabel: "项目摘要",
      openTasksLabel: "待办",
      stateLabel: "状态",
      stageLabel: "阶段",
      taskLabel: "任务",
      heartbeatLabel: "心跳",
    };
  }

  return {
    title: "Collaboration chat",
    subtitle: `Work with ${primaryDisplayName} and the full AI staff room`,
    open: "Open collaboration chat",
    close: "Close collaboration chat",
    refresh: "Refresh",
    autoOn: "Auto refresh: on",
    autoOff: "Auto refresh: off",
    creating: "Creating chat...",
    deleting: "Deleting chat...",
    newChat: "New chat",
    deleteChat: "Delete chat",
    send: "Send",
    terminate: "Stop",
    markDone: "Done",
    markFollowUp: "Follow up",
    markError: "Error",
    attach: "Add files",
    upload: "Uploading",
    mentions: "Mention people",
    route: "Route",
    unread: "Unread",
    typingHint: "Type a message and use @ to route it; without @ it goes to Jarvis first for coordination",
    routeDefault: "Default route: Jarvis coordinates first",
    routePrefix: "Routing to",
    routeAllMembers: "everyone",
    roomLocked: "Write access is off, so switching the live OpenClaw room and sending messages are blocked.",
    roomUnavailable: "This environment has no local write token configured, so the room stays read-only.",
    noEvents: "There are no messages in this chat yet.",
    noRooms: "There are no chats to show yet.",
    save: "Save",
    openFile: "Open",
    download: "Download",
    preview: "Preview",
    queued: "Queued",
    dispatching: "Dispatching",
    idle: "Online",
    failed: "Failed",
    retrying: "Retrying",
    createPrompt: "Name this new chat (optional)",
    projectPrompt: "Name the project for this new chat",
    projectRequired: "A project name is required.",
    deleteConfirm:
      "Delete this chat? This also removes the linked local collaboration record, related local files, and the original OpenClaw chat transcript.",
    sending: "Sending message...",
    terminating: "Stopping current work...",
    adjudicating: "Updating the room status...",
    loading: "Loading collaboration chat...",
    refreshed: "Refreshed",
    writeUnavailable: "Write token unavailable",
    writeLocked: "Write access is off",
    writeReady: "Write access is on",
    pickedFiles: "Picked files",
    remove: "Remove",
    roomsHeading: "Chats",
    participantsHeading: "Participants",
    currentRoom: "Current chat",
    conversation: "Collaboration Room",
    justNow: "Ready",
    projectLabel: "Project",
    projectSummaryLabel: "Summary",
    openTasksLabel: "Open tasks",
    stateLabel: "State",
    stageLabel: "Stage",
    taskLabel: "Task",
    heartbeatLabel: "Heartbeat",
  };
}

export { buildLabels };
